export const DEVICE_TYPE_LABELS: Record<string, string> = {
  polar_h10: "Polar H10",
  polar_h9: "Polar H9",
  polar_oh1: "Polar OH1",
  polar_verity_sense: "Polar Verity Sense",
  polar_generic: "Polar",
  garmin_hrm_pro: "Garmin HRM-Pro",
  garmin_hrm_dual: "Garmin HRM-Dual",
  garmin_hrm_fit: "Garmin HRM-Fit",
  garmin_generic: "Garmin",
  wahoo_tickr: "Wahoo TICKR",
  wahoo_tickr_x: "Wahoo TICKR X",
  wahoo_tickr_fit: "Wahoo TICKR FIT",
  wahoo_generic: "Wahoo",
  suunto_smart_sensor: "Suunto Smart Sensor",
  suunto_generic: "Suunto",
  coospo_h808s: "CooSpo H808S",
  coospo_h6: "CooSpo H6",
  coospo_hw807: "CooSpo HW807",
  coospo_generic: "CooSpo",
  magene_h303: "Magene H303",
  magene_h64: "Magene H64",
  magene_generic: "Magene",
  whoop: "WHOOP",
  movesense: "Movesense",
  scosche_rhythm: "Scosche Rhythm",
  myzone: "Myzone",
  viiiiva: "4iiii Viiiiva",
  moofit: "Moofit",
  generic: "HR Monitor",
};
